/**
 * Let the app talk to the engine on 127.0.0.1, and to nothing else in clear.
 *
 * WHY THIS IS NEEDED AT ALL. Android has refused cleartext HTTP by default
 * since API 28, and whittle's whole arrangement is loopback HTTP: the phone
 * reaches `whittle web` through `adb reverse tcp:8765 tcp:8765`, which arrives
 * at the app as http://127.0.0.1:8765. Without this a release build gets
 * "Cleartext HTTP traffic to 127.0.0.1 not permitted" and every call fails.
 *
 * A debug build already permits it - Expo writes usesCleartextTraffic into the
 * debug manifest - so the failure appears only in the standalone APK that is
 * actually put on the phone, which is the worst place to find it.
 *
 * WHY NOT usesCleartextTraffic="true"
 * -----------------------------------
 * That permits cleartext to EVERY host, and this app has exactly one host it
 * is allowed to reach in clear. A network security config naming the loopback
 * addresses says what is true and leaves the rest of the internet refused, so
 * the app cannot be pointed at a plain-HTTP server somewhere else by accident
 * or otherwise.
 *
 * WHY A PLUGIN AND NOT AN EDIT TO android/
 * ----------------------------------------
 * `android/` is generated and git-ignored. An edit made there is lost by the
 * next `expo prebuild`, and the bug comes back with no trace of the fix ever
 * having existed. Config lives in the config.
 */

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const RESOURCE = 'network_security_config';

/**
 * 127.0.0.1 is the phone's own loopback, which is where `adb reverse` lands.
 * 10.0.2.2 is the host machine as seen from the Android emulator, which is the
 * same engine reached the other way when there is no physical device.
 * `localhost` is named as well because it is what a hostname resolves through
 * and costs nothing to allow alongside the address it resolves to.
 */
const CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED BY plugins/withLoopbackCleartext.js - DO NOT EDIT THIS FILE
  Change the plugin and prebuild the android project again.

  A double dash cannot appear in an XML comment, so the prebuild command is
  described rather than written out: aapt refuses the whole resource file and
  the build fails on a comment.

  whittle reaches its engine over loopback HTTP (adb reverse tcp:8765 tcp:8765).
  Cleartext is permitted to those addresses and refused everywhere else.
-->
<network-security-config>
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">127.0.0.1</domain>
    <domain includeSubdomains="false">localhost</domain>
    <domain includeSubdomains="false">10.0.2.2</domain>
  </domain-config>
  <base-config cleartextTrafficPermitted="false" />
</network-security-config>
`;

module.exports = function withLoopbackCleartext(config) {
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const folder = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(folder, { recursive: true });
      fs.writeFileSync(path.join(folder, `${RESOURCE}.xml`), CONFIG);
      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$['android:networkSecurityConfig'] = `@xml/${RESOURCE}`;
    return cfg;
  });
};
