// GENERATED FROM design/tokens.json - DO NOT EDIT THIS FILE
// Change the token there and run: python tools/tokens.py
//
// Product brief 6.1: the core palette is six values, plus `grid` for the
// graticule, and the pen set is used ONLY inside the 3D canvas and for
// annotation. A pen colour on chrome is a bug, and so is a hex literal
// anywhere else in the app - including a glass alpha.

import { Platform } from 'react-native';

/** The machine's own colours. */
export const core = {
  /** app background, the machine's shell */
  case: '#0B0F0D',
  /** panels, cards, raised surfaces */
  bezel: '#151B18',
  /** rules, borders, grid lines, inactive strokes */
  etch: '#2A322D',
  /** primary accent, active state, primary actions, focused input */
  phosphor: '#FFB000',
  /** primary text */
  screen: '#DCE3DC',
  /** secondary text, labels, disabled */
  dim: '#7C8880',
  /** the graticule ruled over the app ground */
  grid: '#141A17',
} as const;

/**
 * Plotter pens. Canvas and annotation only, and every one is paired with
 * an icon or a label - brief 6.7 forbids colour-only status.
 */
export const pen = {
  /** the printable part */
  solid: '#DCE3DC',
  /** grid, graticule, construction geometry */
  dim: '#4A554E',
  /** reference body from a photo, never printed */
  ref: '#35C6E8',
  /** passed check, confirmed dimension, joint clearance OK */
  pass: '#5BE37D',
  /** tolerance risk, uncalibrated default, thin wall */
  warn: '#FFB000',
  /** failed check, interpenetration, out of bed bounds */
  fail: '#E8489B',
} as const;

/**
 * Two families, and the scale they are set at.
 *
 * These are the families the DEVICE has. The CSS stacks in the token
 * source fall back down a list; a native client gets one name and no
 * fallback, so a font nobody installed is not a near miss - it is the
 * system default, drawn for both families at once.
 */
export const type = {
  /** labels, parameters, numbers, dimensions, the command line, the coordinate readout, buttons */
  mono: Platform.select({ android: 'JetBrains Mono', ios: 'Menlo', default: 'JetBrains Mono' }) as string,
  /** anything longer than two lines */
  prose: Platform.select({ android: 'Space Grotesk', ios: 'System', default: 'Space Grotesk' }) as string,
  size: {
    micro: 10.5,
    label: 12,
    body: 13.5,
    reading: 15,
    figure: 17,
    title: 21,
    display: 27,
  },
  weight: {
    regular: '400' as const,
    medium: '500' as const,
    bold: '600' as const,
  },
} as const;

/** A 4-based scale. Every gap in the app is one of these. */
export const space = {
  hair: 2,
  tight: 4,
  snug: 8,
  base: 12,
  wide: 16,
  loose: 24,
  room: 32,
  hall: 48,
} as const;

/** Squared-off rather than pill-shaped: a machine, not a toy. */
export const radius = {
  none: 0,
  edge: 3,
  panel: 6,
  control: 7,
  card: 10,
  float: 16,
} as const;

/**
 * The glass layer. Design handoff section 6, an accepted amendment to
 * product brief 6.6.
 *
 * Every raised surface is glass; the ground, the 3D canvas and INK are
 * not. Text, numbers, callouts, sliders and check marks are full opacity
 * always - glass is the surface under a value, never the value.
 *
 * Compose these through the Glass component. A view that builds its own
 * blur is the bug this module exists to prevent.
 */
export const glass = {
  /** The fill every glass surface is built from, at its step's alpha. */
  tint: (alpha: number) => `rgba(30, 38, 34, ${alpha})`,
  /** The hairline border on neutral glass. */
  hairline: (alpha: number = 0.12) => `rgba(220, 227, 220, ${alpha})`,
  /** The light catching the top edge of the pane. */
  highlight: (alpha: number = 0.08) => `rgba(220, 227, 220, ${alpha})`,
  saturate: 150,
} as const;

/**
 * The five depths, shallowest first. A surface over CONTENT is denser
 * than one over the GROUND - that is what these are, not five greys.
 * Do not go below a step's alpha.
 */
export const depth = {
  /** sits over the ground: web side columns, scrollback, the photo-fit invitation */
  panel: { alpha: 0.35, blur: 18, radius: radius.card },
  /** recessed in a panel: field wells, segmented controls, rail items */
  well: { alpha: 0.36, blur: 14, radius: radius.control },
  /** library cards, plan cards, notes, the credits panel, the avatar */
  card: { alpha: 0.44, blur: 16, radius: radius.card },
  /** over the viewport: the composer, viewport pills, browser chrome */
  pill: { alpha: 0.48, blur: 18, radius: radius.control },
  /** over everything: the bottom sheet, the device bezel, the tab bar, the web status line */
  float: { alpha: 0.56, blur: 24, radius: radius.float },
} as const;

/**
 * Tinted glass: same blur, keeps its hue, and the border takes the tint
 * rather than the neutral hairline - which is why the two alphas differ.
 */
export const tinted = {
  /** the clearance callout, the active plan card */
  warn: { rgb: [255, 176, 0] as const, alpha: 0.1, borderAlpha: 0.65 },
  /** the pipeline banner, anything about a reference body */
  ref: { rgb: [53, 198, 232] as const, alpha: 0.1, borderAlpha: 0.45 },
  /** a pill or segment in its selected state */
  active: { rgb: [255, 176, 0] as const, alpha: 0.18, borderAlpha: 0.7 },
} as const;

/**
 * Ambient light BEHIND the glass. Not decoration: a blur with nothing to
 * pick up renders as flat grey, and every panel becomes one slab.
 *
 * `at` and `size` are fractions of the box, width then height, which is
 * CSS's two radial-gradient percentages - an ellipse, not a circle.
 */
export const ambient = [
  {
    rgb: [255, 176, 0] as const,
    alpha: 0.2,
    at: [0.78, 0.04] as const,
    size: [1.2, 0.6] as const,
    stop: 0.62,
  },
  {
    rgb: [53, 198, 232] as const,
    alpha: 0.16,
    at: [0.1, 0.96] as const,
    size: [0.9, 0.44] as const,
    stop: 0.66,
  },
  {
    rgb: [255, 176, 0] as const,
    alpha: 0.07,
    at: [0.12, 0.46] as const,
    size: [0.8, 0.4] as const,
    stop: 0.7,
  },
] as const;

/** Constants the brief pins, so no client invents one. */
export const metric = {
  tap: 44,
  minWidth: 380,
} as const;
