"""
Write the GLB files app/tests/glb.test.ts reads, and the truth about them.

    python tools/glb_fixtures.py

WHY THE FIXTURES ARE GENERATED AND CHECKED IN
----------------------------------------------
The React Native client parses GLB itself (app/src/glb.ts), for the reason
written at the top of that file. A reader tested against a GLB it also wrote
proves nothing, so the fixtures come from the engine's own export path - the
same whittle.web.projects.to_glb the /preview route calls - and the expectations
come from trimesh measuring the mesh, not from the exporter.

They are committed rather than generated at test time so `npm test` needs no
Python and no conda environment. Regenerate them when the export path changes;
tests/test_glb_fixtures.py fails if they have gone stale, which is the same
arrangement design/tokens.json has with its exports.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "app" / "tests" / "fixtures"

BANNER = ("GENERATED BY tools/glb_fixtures.py FROM THE ENGINE'S OWN EXPORT - "
          "DO NOT EDIT")


def _cases():
    """
    The shapes worth pinning, and why each one is here.

    Each is (name, mesh). Nothing exotic: the point is coverage of what the
    reader has to get right, not of what trimesh can build.
    """
    import numpy as np
    import trimesh

    # A BOX. Eight vertices, uint32 indices, no normals - the exact shape of
    # every preview the server sends, and the one measured by hand in the
    # session that wrote the reader.
    box = trimesh.creation.box((80.0, 40.0, 6.0))

    # A SPHERE. Enough triangles that a stride mistake shows up as noise
    # rather than as a plausible-looking box, and the shape whose poles once
    # produced two zero-area facets and a mesh that was never watertight.
    sphere = trimesh.creation.icosphere(subdivisions=3, radius=20.0)

    # TWO BODIES, OFF THE ORIGIN. A cut model is the product's own output and
    # it arrives as several lumps in one scene. Moving them away from the
    # origin is what catches a node transform being dropped: with both bodies
    # at the origin, ignoring the matrix entirely still looks right.
    left = trimesh.creation.box((30.0, 30.0, 30.0))
    left.apply_translation((-40.0, 0.0, 15.0))
    right = trimesh.creation.box((30.0, 30.0, 30.0))
    right.apply_translation((40.0, 0.0, 15.0))
    pair = trimesh.util.concatenate([left, right])

    # A TALL THING WELL AWAY FROM THE ORIGIN. The bug this pins is the one
    # that cost a cut plane: geometry reasoned about by extents rather than
    # by bounds looks correct until the model is not centred.
    lifted = trimesh.creation.cylinder(radius=12.0, height=90.0)
    lifted.apply_translation((0.0, 0.0, 400.0))

    return [
        ("box", box),
        ("sphere", sphere),
        ("two-bodies", pair),
        ("lifted-cylinder", lifted),
    ]


def main() -> int:
    import numpy as np

    from whittle.web.projects import to_glb

    OUT.mkdir(parents=True, exist_ok=True)
    manifest = {"$comment": BANNER, "cases": []}

    for name, mesh in _cases():
        data = to_glb(mesh)
        (OUT / ("%s.glb" % name)).write_bytes(data)

        # THE EXPECTATIONS COME FROM THE MESH, NOT FROM THE GLB. Reading them
        # back out of the file being tested would only prove the file is
        # self-consistent.
        bounds = np.asarray(mesh.bounds, dtype=float)
        manifest["cases"].append({
            "name": name,
            "file": "%s.glb" % name,
            "bytes": len(data),
            "triangles": int(len(mesh.faces)),
            "vertices": int(len(mesh.vertices)),
            "min": [round(float(v), 6) for v in bounds[0]],
            "max": [round(float(v), 6) for v in bounds[1]],
            "centroid": [round(float(v), 6) for v in mesh.centroid],
            "area_mm2": round(float(mesh.area), 6),
        })

    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    for case in manifest["cases"]:
        print("wrote %s  %s triangles, %s bytes"
              % (case["file"], format(case["triangles"], ","),
                 format(case["bytes"], ",")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
