"""
design/tokens.json -> CSS custom properties, Dart constants, TypeScript constants.

    python tools/tokens.py            write every export
    python tools/tokens.py --check    fail if any is stale, write nothing

WHY A BUILD STEP AND NOT TWO HAND-KEPT FILES
--------------------------------------------
Product brief 2.6. Two clients shipping in parallel drift the moment a hex
value exists in two places, and the brief calls a colour that differs between
web and native a bug rather than an inconsistency. Acceptance criterion 10 is
that a token change in the shared source updates both.

--check is what makes that real: tests/test_tokens.py runs it, so a token
edited in the source and not exported is a test failure, not a visual surprise
noticed three screens later.

THE GENERATED FILES ARE NOT EDITED. Both carry a header saying so and naming
this script. That is the only defence against somebody fixing a colour in the
CSS, which then silently disagrees with Dart until a screenshot catches it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "tokens.json"
CSS_OUT = ROOT / "whittle" / "web" / "static" / "tokens.css"
DART_OUT = ROOT / "mobile" / "lib" / "tokens.dart"
TS_OUT = ROOT / "app" / "src" / "tokens.ts"

BANNER = "GENERATED FROM design/tokens.json - DO NOT EDIT THIS FILE"
REGENERATE = "Change the token there and run: python tools/tokens.py"


def load() -> dict[str, Any]:
    if not SOURCE.is_file():
        raise SystemExit("no token source at %s" % SOURCE)
    return json.loads(SOURCE.read_text())


def _clean(section: dict[str, Any]) -> dict[str, Any]:
    """Drop the $comment keys; they document the source, not the output."""
    return {k: v for k, v in section.items() if not k.startswith("$")}


def _hexes(section: dict[str, Any]) -> dict[str, str]:
    return {k: v["hex"] for k, v in _clean(section).items()}


# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

def to_css(tokens: dict[str, Any]) -> str:
    lines = [
        "/*",
        " * %s" % BANNER,
        " * %s" % REGENERATE,
        " *",
        " * Product brief 6.1: the core palette is six values, plus `grid` for the",
        " * graticule, and the pen set is used ONLY inside the 3D canvas and for",
        " * annotation. A pen colour on chrome is a bug, and so is a hex literal",
        " * anywhere else in the CSS - including a glass alpha.",
        " */",
        "",
        ":root {",
    ]

    lines.append("  /* core palette */")
    core = _clean(tokens["core"])
    pad = max(len(n) for n in core) + len("  --bp-: #000000;")
    for name, value in core.items():
        declaration = "  --bp-%s: %s;" % (name, value["hex"])
        lines.append("%-*s /* %s */" % (pad, declaration, value["use"]))

    lines.append("")
    lines.append("  /* viewport pen set - canvas and annotation only */")
    pens = _clean(tokens["pen"])
    pad = max(len(n) for n in pens) + len("  --bp-pen-: #000000;")
    for name, value in pens.items():
        declaration = "  --bp-pen-%s: %s;" % (name, value["hex"])
        lines.append("%-*s /* %s */" % (pad, declaration, value["meaning"]))

    lines.append("")
    lines.append("  /* type */")
    lines.append("  --bp-mono: %s;" % tokens["type"]["mono"]["stack"])
    lines.append("  --bp-prose: %s;" % tokens["type"]["prose"]["stack"])
    for name, size in _clean(tokens["type"]["scale"]).items():
        lines.append("  --bp-text-%s: %gpx;" % (name, size))
    for name, weight in _clean(tokens["type"]["weight"]).items():
        lines.append("  --bp-weight-%s: %d;" % (name, weight))

    lines.append("")
    lines.append("  /* spacing */")
    for name, size in _clean(tokens["space"]).items():
        lines.append("  --bp-space-%s: %gpx;" % (name, size))

    lines.append("")
    lines.append("  /* radii */")
    for name, size in _clean(tokens["radius"]).items():
        lines.append("  --bp-radius-%s: %gpx;" % (name, size))

    lines.append("")
    lines.extend(_css_glass(tokens["glass"]))

    lines.append("")
    lines.append("  /* pinned metrics */")
    for name, size in _clean(tokens["metric"]).items():
        lines.append("  --bp-%s: %gpx;" % (name.replace("_", "-"), size))

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _rgb(triplet: list[int]) -> str:
    """
    SPACE-SEPARATED, and that is not a style choice.

    These triplets are composed as `rgb(var(--bp-glass-tint) / <alpha>)` so a
    single tint can be reused at five alphas. That slash form is CSS Color 4,
    which requires space-separated channels: with commas the declaration
    becomes `rgb(30, 38, 34 / 0.56)`, which is invalid and computes to
    transparent - so every glass surface rendered as nothing at all, with no
    error anywhere and the blur still visibly working behind it.
    """
    return " ".join(str(c) for c in triplet)


def _css_glass(glass: dict[str, Any]) -> list[str]:
    """
    The glass layer, as raw values for ONE primitive to compose.

    Deliberately not emitted as five ready-made `background` declarations. The
    handoff's rule is that every screen composes a single glass primitive and
    nothing sets backdrop-filter inline, so what belongs here is the tint, the
    alphas and the blurs - and app.css builds the surfaces from them. Exported
    as a colour per step, the tint could not be retuned in one place, which is
    the whole reason it is a token.
    """
    lines = ["  /* glass: the raw values, composed by the .glass primitive in app.css */"]
    lines.append("  --bp-glass-tint: %s;" % _rgb(glass["tint"]["rgb"]))
    lines.append("  --bp-glass-hairline: %s;" % _rgb(glass["hairline"]["rgb"]))
    lines.append("  --bp-glass-hairline-alpha: %g;" % glass["hairline"]["alpha"])
    lines.append("  --bp-glass-highlight: %s;" % _rgb(glass["highlight"]["rgb"]))
    lines.append("  --bp-glass-highlight-alpha: %g;" % glass["highlight"]["alpha"])
    lines.append("  --bp-glass-saturate: %g%%;" % glass["saturate"])

    lines.append("")
    lines.append("  /* the five depths - a surface over content is denser than one over the ground */")
    for name, step in _clean(glass["surface"]).items():
        lines.append("  --bp-glass-%s-alpha: %g;   /* %s */"
                     % (name, step["alpha"], step["use"]))
        lines.append("  --bp-glass-%s-blur: %gpx;" % (name, step["blur"]))
        lines.append("  --bp-glass-%s-radius: var(--bp-radius-%s);"
                     % (name, step["radius"]))

    lines.append("")
    lines.append("  /* tinted glass: same blur, keeps its hue, border takes the tint */")
    for name, tint in _clean(glass["tinted"]).items():
        lines.append("  --bp-glass-%s: %s;" % (name, _rgb(tint["rgb"])))
        lines.append("  --bp-glass-%s-alpha: %g;" % (name, tint["alpha"]))
        lines.append("  --bp-glass-%s-border-alpha: %g;"
                     % (name, tint["border_alpha"]))

    # The ambient wash is one value because it is one background-image: a blur
    # with nothing behind it to pick up renders as flat grey.
    washes = ",\n    ".join(
        "radial-gradient(%s at %s, rgba(%s, %g), transparent %s)"
        % (layer["size"], layer["at"], _rgb(layer["rgb"]),
           layer["alpha"], layer["stop"])
        for layer in glass["ambient"]["layers"]
    )
    lines.append("")
    lines.append("  /* ambient light BEHIND the glass. Without it every panel reads flat. */")
    lines.append("  --bp-ambient:\n    %s;" % washes)
    return lines


# ---------------------------------------------------------------------------
# Dart
# ---------------------------------------------------------------------------

def _dart_colour(hex_value: str) -> str:
    return "Color(0xFF%s)" % hex_value.lstrip("#").upper()


# DART RESERVED WORDS THAT COLLIDE WITH TOKEN NAMES.
#
# The brief's first colour is called `case` - the machine's shell - and `case`
# is a Dart keyword, so the generated file would not compile. Caught by
# generating it rather than by reading it, which is the argument for the build
# step existing at all.
#
# Renaming the token in the source would be worse: the name comes from the
# brief and web keeps it. So the Dart identifier gains a suffix and says why,
# and the mapping is written here rather than special-cased at the call site.
DART_RESERVED = {
    "case": "caseColor",
    "class": "classColor",
    "default": "defaultValue",
    "in": "inValue",
    "is": "isValue",
    "new": "newValue",
    "null": "nullValue",
    "switch": "switchValue",
    "this": "thisValue",
    "var": "varValue",
    "void": "voidValue",
    "with": "withValue",
    "final": "finalValue",
    "const": "constValue",
    "static": "staticValue",
    "enum": "enumValue",
    "extends": "extendsValue",
    "super": "superValue",
    "true": "trueValue",
    "false": "falseValue",
}


def _camel(name: str) -> str:
    head, *rest = name.split("_")
    camel = head + "".join(p.title() for p in rest)
    return DART_RESERVED.get(camel, camel)


def to_dart(tokens: dict[str, Any]) -> str:
    lines = [
        "// %s" % BANNER,
        "// %s" % REGENERATE,
        "//",
        "// Product brief 6.1: the core palette is six values, plus `grid` for the",
        "// graticule, and the pen set is used ONLY inside the 3D canvas and for",
        "// annotation. A pen colour on chrome is a bug, and so is a Color literal",
        "// anywhere else in the app - including a glass alpha.",
        "",
        # painting rather than dart:ui: Color comes from either, but the
        # ambient washes are positioned with Alignment, which is Flutter's.
        "import 'package:flutter/painting.dart';",
        "",
        "/// The machine's own colours.",
        "class BpCore {",
        "  BpCore._();",
        "",
    ]
    for name, value in _clean(tokens["core"]).items():
        lines.append("  /// %s" % value["use"])
        lines.append("  static const Color %s = %s;"
                     % (_camel(name), _dart_colour(value["hex"])))
        lines.append("")
    lines.append("}")
    lines.append("")

    lines += [
        "/// Plotter pens. Canvas and annotation only, and every one is paired",
        "/// with an icon or a label - brief 6.7 forbids colour-only status.",
        "class BpPen {",
        "  BpPen._();",
        "",
    ]
    for name, value in _clean(tokens["pen"]).items():
        lines.append("  /// %s" % value["meaning"])
        lines.append("  static const Color %s = %s;"
                     % (_camel(name), _dart_colour(value["hex"])))
        lines.append("")
    lines.append("}")
    lines.append("")

    mono = tokens["type"]["mono"]["stack"].split(",")[0].strip().strip("'\"")
    prose = tokens["type"]["prose"]["stack"].split(",")[0].strip().strip("'\"")
    lines += [
        "/// Two families, and the scale they are set at.",
        "class BpType {",
        "  BpType._();",
        "",
        "  /// %s" % tokens["type"]["mono"]["use"],
        "  static const String mono = '%s';" % mono,
        "",
        "  /// %s" % tokens["type"]["prose"]["use"],
        "  static const String prose = '%s';" % prose,
        "",
    ]
    for name, size in _clean(tokens["type"]["scale"]).items():
        lines.append("  static const double %s = %g;" % (_camel(name), size))
    lines.append("")
    for name, weight in _clean(tokens["type"]["weight"]).items():
        lines.append("  static const int weight%s = %d;"
                     % (name.title(), weight))
    lines.append("}")
    lines.append("")

    lines += ["/// A 4-based scale. Every gap in the app is one of these.",
              "class BpSpace {", "  BpSpace._();", ""]
    for name, size in _clean(tokens["space"]).items():
        lines.append("  static const double %s = %g;" % (_camel(name), size))
    lines.append("}")
    lines.append("")

    lines += ["/// Squared-off rather than pill-shaped: a machine, not a toy.",
              "class BpRadius {", "  BpRadius._();", ""]
    for name, size in _clean(tokens["radius"]).items():
        lines.append("  static const double %s = %g;" % (_camel(name), size))
    lines.append("}")
    lines.append("")

    lines += _dart_glass(tokens["glass"])

    lines += ["/// Constants the brief pins, so neither client invents one.",
              "class BpMetric {", "  BpMetric._();", ""]
    for name, size in _clean(tokens["metric"]).items():
        lines.append("  static const double %s = %g;" % (_camel(name), size))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _dart_glass(glass: dict[str, Any]) -> list[str]:
    """
    The glass layer for Flutter.

    `tint(alpha)` is a function rather than five constants for the same reason
    the CSS exports a triplet: a theme change has to move all of it at once.
    The five depths are then just alpha and blur pairs that GlassSurface
    composes - no widget builds its own BackdropFilter.
    """
    tint = glass["tint"]["rgb"]
    hairline = glass["hairline"]["rgb"]
    highlight = glass["highlight"]["rgb"]

    lines = [
        "/// The glass layer. Design handoff section 6, an accepted amendment to",
        "/// product brief 6.6.",
        "///",
        "/// Every raised surface is glass; the ground, the 3D canvas and INK are",
        "/// not. Text, numbers, callouts, sliders and check marks are full",
        "/// opacity always - glass is the surface under a value, never the value.",
        "///",
        "/// Compose these through GlassSurface. A widget that builds its own",
        "/// BackdropFilter is the bug this class exists to prevent.",
        "class BpGlass {",
        "  BpGlass._();",
        "",
        "  /// The fill every glass surface is built from, at its step's alpha.",
        "  /// A function, not five constants: a theme change moves all of it.",
        "  static Color tint(double alpha) =>",
        "      const Color.fromARGB(255, %d, %d, %d).withValues(alpha: alpha);"
        % tuple(tint),
        "",
        "  /// The 1px border on neutral glass.",
        "  static Color hairline([double alpha = %g]) =>"
        % glass["hairline"]["alpha"],
        "      const Color.fromARGB(255, %d, %d, %d).withValues(alpha: alpha);"
        % tuple(hairline),
        "",
        "  /// The light catching the top edge of the pane.",
        "  static Color highlight([double alpha = %g]) =>"
        % glass["highlight"]["alpha"],
        "      const Color.fromARGB(255, %d, %d, %d).withValues(alpha: alpha);"
        % tuple(highlight),
        "",
        "  static const double saturate = %g;" % glass["saturate"],
        "}",
        "",
        "/// The five depths, shallowest first. A surface over CONTENT is denser",
        "/// than one over the GROUND - that is what these are, not five greys.",
        "/// Do not go below a step's alpha.",
        "enum GlassDepth {",
    ]
    steps = _clean(glass["surface"])
    for index, (name, step) in enumerate(steps.items()):
        end = "," if index < len(steps) - 1 else ";"
        lines.append("  /// %s" % step["use"])
        lines.append("  %s(alpha: %g, blur: %g, radius: BpRadius.%s)%s"
                     % (_camel(name), step["alpha"], step["blur"],
                        _camel(step["radius"]), end))
    lines += [
        "",
        "  const GlassDepth({",
        "    required this.alpha,",
        "    required this.blur,",
        "    required this.radius,",
        "  });",
        "",
        "  final double alpha;",
        "  final double blur;",
        "  final double radius;",
        "}",
        "",
        "/// Tinted glass: same blur, keeps its hue, and the border takes the tint",
        "/// rather than the neutral hairline - which is why the two alphas differ.",
        "enum GlassTint {",
    ]
    tints = _clean(glass["tinted"])
    for index, (name, value) in enumerate(tints.items()):
        end = "," if index < len(tints) - 1 else ";"
        lines.append("  /// %s" % value["use"])
        lines.append("  %s(color: Color(0xFF%02X%02X%02X), alpha: %g, "
                     "borderAlpha: %g)%s"
                     % (_camel(name), *value["rgb"], value["alpha"],
                        value["border_alpha"], end))
    lines += [
        "",
        "  const GlassTint({",
        "    required this.color,",
        "    required this.alpha,",
        "    required this.borderAlpha,",
        "  });",
        "",
        "  final Color color;",
        "  final double alpha;",
        "  final double borderAlpha;",
        "",
        "  Color get fill => color.withValues(alpha: alpha);",
        "  Color get border => color.withValues(alpha: borderAlpha);",
        "}",
        "",
        "/// Ambient light BEHIND the glass. Not decoration: a blur with nothing",
        "/// to pick up renders as flat grey, and every panel becomes one slab.",
        "class BpAmbient {",
        "  BpAmbient._();",
        "",
    ]
    for index, layer in enumerate(glass["ambient"]["layers"]):
        lines.append("  static const Color wash%d = "
                     "Color(0xFF%02X%02X%02X);" % (index, *layer["rgb"]))
        lines.append("  static const double wash%dAlpha = %g;"
                     % (index, layer["alpha"]))
        lines.append("  /// Fractional centre of the wash, as (x, y) of the box.")
        lines.append("  static const Alignment wash%dAt = Alignment(%g, %g);"
                     % (index,
                        _fraction(layer["at"], 0), _fraction(layer["at"], 1)))
        lines.append("  /// The wash's extent as a fraction of the box, width")
        lines.append("  /// then height - CSS's two radial-gradient")
        lines.append("  /// percentages, which is an ellipse and not a circle.")
        lines.append("  static const Size wash%dSize = Size(%g, %g);"
                     % (index,
                        _percent(layer["size"], 0), _percent(layer["size"], 1)))
        lines.append("  /// Where the wash has fallen to nothing.")
        lines.append("  static const double wash%dStop = %g;"
                     % (index, _percent(layer["stop"], 0)))
        lines.append("")
    lines.append("}")
    lines.append("")
    return lines


def _percent(value: str, index: int) -> float:
    """"120% 60%" -> 1.2 or 0.6. A plain fraction of the box."""
    return round(float(value.split()[index].rstrip("%")) / 100.0, 4)


def _fraction(at: str, index: int) -> float:
    """
    "78% 4%" -> Flutter's Alignment, which runs -1 to 1 rather than 0 to 100.

    The percentages are written once, in the token source, in CSS's terms
    because that is where the design specifies them. Converting here keeps the
    two clients reading one number instead of two that can drift.
    """
    percent = float(at.split()[index].rstrip("%"))
    return round(percent / 50.0 - 1.0, 4)


# ---------------------------------------------------------------------------
# TypeScript
# ---------------------------------------------------------------------------

def _ts_name(name: str) -> str:
    """
    camelCase, and no reserved-word table.

    Dart needed one because `case` is a keyword there at any position. In
    TypeScript these are object PROPERTIES, and a property may be called
    `case` or `default` or `new` - so the brief's names survive intact, which
    is what everybody wants when they are reading the design next to the code.
    """
    head, *rest = name.split("_")
    return head + "".join(p.title() for p in rest)


def to_ts(tokens: dict[str, Any]) -> str:
    """
    The same values again, for React Native and later for the web app.

    NUMBERS, NOT STRINGS WITH `px`. React Native's style values are unitless
    density-independent pixels, so a `'12px'` here is not a smaller gap, it is
    a style RN silently drops - and the CSS export already carries the unit
    for the client that needs one.

    Colours stay as hex strings because RN and the DOM both take them, and
    because a triplet would have to be reassembled at every call site.
    """
    core = _hexes(tokens["core"])
    pens = _hexes(tokens["pen"])
    glass = tokens["glass"]

    lines = [
        "// %s" % BANNER,
        "// %s" % REGENERATE,
        "//",
        "// Product brief 6.1: the core palette is six values, plus `grid` for the",
        "// graticule, and the pen set is used ONLY inside the 3D canvas and for",
        "// annotation. A pen colour on chrome is a bug, and so is a hex literal",
        "// anywhere else in the app - including a glass alpha.",
        "",
        "import { Platform } from 'react-native';",
        "",
        "/** The machine's own colours. */",
        "export const core = {",
    ]
    for name, value in _clean(tokens["core"]).items():
        lines.append("  /** %s */" % value["use"])
        lines.append("  %s: '%s'," % (_ts_name(name), value["hex"]))
    lines.append("} as const;")
    lines.append("")

    lines += [
        "/**",
        " * Plotter pens. Canvas and annotation only, and every one is paired with",
        " * an icon or a label - brief 6.7 forbids colour-only status.",
        " */",
        "export const pen = {",
    ]
    for name, value in _clean(tokens["pen"]).items():
        lines.append("  /** %s */" % value["meaning"])
        lines.append("  %s: '%s'," % (_ts_name(name), value["hex"]))
    lines.append("} as const;")
    lines.append("")

    # THE NATIVE FAMILY, NOT THE HEAD OF THE CSS STACK. React Native takes one
    # family name and has no fallback list: a name the device does not have is
    # drawn in the system default, silently. Taking `stack[0]` asked Android
    # for 'IBM Plex Mono' and 'Inter', got neither, and rendered the two
    # families identically - which is the one thing the type tokens exist to
    # prevent. `native` names what the platform actually ships.
    mono = tokens["type"]["mono"]["native"]
    prose = tokens["type"]["prose"]["native"]

    def family(spec: dict) -> str:
        return ("Platform.select({ android: '%s', ios: '%s', "
                "default: '%s' }) as string" % (spec["android"], spec["ios"],
                                                spec["android"]))

    lines += [
        "/**",
        " * Two families, and the scale they are set at.",
        " *",
        " * These are the families the DEVICE has. The CSS stacks in the token",
        " * source fall back down a list; a native client gets one name and no",
        " * fallback, so a font nobody installed is not a near miss - it is the",
        " * system default, drawn for both families at once.",
        " */",
        "export const type = {",
        "  /** %s */" % tokens["type"]["mono"]["use"],
        "  mono: %s," % family(mono),
        "  /** %s */" % tokens["type"]["prose"]["use"],
        "  prose: %s," % family(prose),
        "  size: {",
    ]
    for name, size in _clean(tokens["type"]["scale"]).items():
        lines.append("    %s: %g," % (_ts_name(name), size))
    lines.append("  },")
    lines.append("  weight: {")
    for name, weight in _clean(tokens["type"]["weight"]).items():
        # RN wants fontWeight as a string, and '400' is not assignable from
        # `number` in its types - so these are emitted as strings on purpose.
        lines.append("    %s: '%d' as const," % (_ts_name(name), weight))
    lines.append("  },")
    lines.append("} as const;")
    lines.append("")

    lines.append("/** A 4-based scale. Every gap in the app is one of these. */")
    lines.append("export const space = {")
    for name, size in _clean(tokens["space"]).items():
        lines.append("  %s: %g," % (_ts_name(name), size))
    lines.append("} as const;")
    lines.append("")

    lines.append("/** Squared-off rather than pill-shaped: a machine, not a toy. */")
    lines.append("export const radius = {")
    for name, size in _clean(tokens["radius"]).items():
        lines.append("  %s: %g," % (_ts_name(name), size))
    lines.append("} as const;")
    lines.append("")

    lines += _ts_glass(glass)

    lines.append("/** Constants the brief pins, so no client invents one. */")
    lines.append("export const metric = {")
    for name, size in _clean(tokens["metric"]).items():
        lines.append("  %s: %g," % (_ts_name(name), size))
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def _ts_glass(glass: dict[str, Any]) -> list[str]:
    """
    The glass layer for React Native.

    `tint(alpha)` is a function for the same reason it is in Dart and a
    triplet in CSS: one theme change has to move all of it. What differs is
    what the platform can do - Android has no backdrop blur in a plain View,
    so `blur` is exported for the component to use where it can and the alpha
    carries the surface on its own where it cannot. That is why the alpha and
    the blur are separate numbers rather than one baked colour.
    """
    tint = glass["tint"]["rgb"]
    hairline = glass["hairline"]["rgb"]
    highlight = glass["highlight"]["rgb"]

    lines = [
        "/**",
        " * The glass layer. Design handoff section 6, an accepted amendment to",
        " * product brief 6.6.",
        " *",
        " * Every raised surface is glass; the ground, the 3D canvas and INK are",
        " * not. Text, numbers, callouts, sliders and check marks are full opacity",
        " * always - glass is the surface under a value, never the value.",
        " *",
        " * Compose these through the Glass component. A view that builds its own",
        " * blur is the bug this module exists to prevent.",
        " */",
        "export const glass = {",
        "  /** The fill every glass surface is built from, at its step's alpha. */",
        "  tint: (alpha: number) => `rgba(%d, %d, %d, ${alpha})`," % tuple(tint),
        "  /** The hairline border on neutral glass. */",
        "  hairline: (alpha: number = %g) => `rgba(%d, %d, %d, ${alpha})`,"
        % (glass["hairline"]["alpha"], *hairline),
        "  /** The light catching the top edge of the pane. */",
        "  highlight: (alpha: number = %g) => `rgba(%d, %d, %d, ${alpha})`,"
        % (glass["highlight"]["alpha"], *highlight),
        "  saturate: %g," % glass["saturate"],
        "} as const;",
        "",
        "/**",
        " * The five depths, shallowest first. A surface over CONTENT is denser",
        " * than one over the GROUND - that is what these are, not five greys.",
        " * Do not go below a step's alpha.",
        " */",
        "export const depth = {",
    ]
    for name, step in _clean(glass["surface"]).items():
        lines.append("  /** %s */" % step["use"])
        lines.append("  %s: { alpha: %g, blur: %g, radius: radius.%s },"
                     % (_ts_name(name), step["alpha"], step["blur"],
                        _ts_name(step["radius"])))
    lines.append("} as const;")
    lines.append("")

    lines += [
        "/**",
        " * Tinted glass: same blur, keeps its hue, and the border takes the tint",
        " * rather than the neutral hairline - which is why the two alphas differ.",
        " */",
        "export const tinted = {",
    ]
    for name, value in _clean(glass["tinted"]).items():
        lines.append("  /** %s */" % value["use"])
        lines.append("  %s: { rgb: [%d, %d, %d] as const, alpha: %g, "
                     "borderAlpha: %g },"
                     % (_ts_name(name), *value["rgb"], value["alpha"],
                        value["border_alpha"]))
    lines.append("} as const;")
    lines.append("")

    lines += [
        "/**",
        " * Ambient light BEHIND the glass. Not decoration: a blur with nothing to",
        " * pick up renders as flat grey, and every panel becomes one slab.",
        " *",
        " * `at` and `size` are fractions of the box, width then height, which is",
        " * CSS's two radial-gradient percentages - an ellipse, not a circle.",
        " */",
        "export const ambient = [",
    ]
    for layer in glass["ambient"]["layers"]:
        lines.append("  {")
        lines.append("    rgb: [%d, %d, %d] as const," % tuple(layer["rgb"]))
        lines.append("    alpha: %g," % layer["alpha"])
        lines.append("    at: [%g, %g] as const,"
                     % (_percent(layer["at"], 0), _percent(layer["at"], 1)))
        lines.append("    size: [%g, %g] as const,"
                     % (_percent(layer["size"], 0), _percent(layer["size"], 1)))
        lines.append("    stop: %g," % _percent(layer["stop"], 0))
        lines.append("  },")
    lines.append("] as const;")
    lines.append("")
    return lines


# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--check", action="store_true",
                        help="fail if an export is stale; write nothing")
    args = parser.parse_args(argv)

    tokens = load()
    wanted = {CSS_OUT: to_css(tokens), DART_OUT: to_dart(tokens),
              TS_OUT: to_ts(tokens)}

    if args.check:
        stale = [
            path for path, text in wanted.items()
            if not path.is_file() or path.read_text() != text
        ]
        if stale:
            print("stale token exports:")
            for path in stale:
                print("  %s" % path.relative_to(ROOT))
            print("\nrun: python tools/tokens.py")
            return 1
        print("token exports are current")
        return 0

    for path, text in wanted.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print("wrote %s" % path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
