// GENERATED FROM design/tokens.json - DO NOT EDIT THIS FILE
// Change the token there and run: python tools/tokens.py
//
// Product brief 6.1: the core palette is six values, plus `grid` for the
// graticule, and the pen set is used ONLY inside the 3D canvas and for
// annotation. A pen colour on chrome is a bug, and so is a Color literal
// anywhere else in the app - including a glass alpha.

import 'package:flutter/painting.dart';

/// The machine's own colours.
class BpCore {
  BpCore._();

  /// app background, the machine's shell
  static const Color caseColor = Color(0xFF0B0F0D);

  /// panels, cards, raised surfaces
  static const Color bezel = Color(0xFF151B18);

  /// rules, borders, grid lines, inactive strokes
  static const Color etch = Color(0xFF2A322D);

  /// primary accent, active state, primary actions, focused input
  static const Color phosphor = Color(0xFFFFB000);

  /// primary text
  static const Color screen = Color(0xFFDCE3DC);

  /// secondary text, labels, disabled
  static const Color dim = Color(0xFF7C8880);

  /// the graticule ruled over the app ground
  static const Color grid = Color(0xFF141A17);

}

/// Plotter pens. Canvas and annotation only, and every one is paired
/// with an icon or a label - brief 6.7 forbids colour-only status.
class BpPen {
  BpPen._();

  /// the printable part
  static const Color solid = Color(0xFFDCE3DC);

  /// grid, graticule, construction geometry
  static const Color dim = Color(0xFF4A554E);

  /// reference body from a photo, never printed
  static const Color ref = Color(0xFF35C6E8);

  /// passed check, confirmed dimension, joint clearance OK
  static const Color pass = Color(0xFF5BE37D);

  /// tolerance risk, uncalibrated default, thin wall
  static const Color warn = Color(0xFFFFB000);

  /// failed check, interpenetration, out of bed bounds
  static const Color fail = Color(0xFFE8489B);

}

/// Two families, and the scale they are set at.
class BpType {
  BpType._();

  /// labels, parameters, numbers, dimensions, the command line, the coordinate readout, buttons
  static const String mono = 'IBM Plex Mono';

  /// anything longer than two lines
  static const String prose = 'Inter';

  static const double micro = 10.5;
  static const double label = 12;
  static const double body = 13.5;
  static const double reading = 15;
  static const double figure = 17;
  static const double title = 21;
  static const double display = 27;

  static const int weightRegular = 400;
  static const int weightMedium = 500;
  static const int weightBold = 600;
}

/// A 4-based scale. Every gap in the app is one of these.
class BpSpace {
  BpSpace._();

  static const double hair = 2;
  static const double tight = 4;
  static const double snug = 8;
  static const double base = 12;
  static const double wide = 16;
  static const double loose = 24;
  static const double room = 32;
  static const double hall = 48;
}

/// Squared-off rather than pill-shaped: a machine, not a toy.
class BpRadius {
  BpRadius._();

  static const double none = 0;
  static const double edge = 3;
  static const double panel = 6;
  static const double control = 7;
  static const double card = 10;
  static const double float = 16;
}

/// The glass layer. Design handoff section 6, an accepted amendment to
/// product brief 6.6.
///
/// Every raised surface is glass; the ground, the 3D canvas and INK are
/// not. Text, numbers, callouts, sliders and check marks are full
/// opacity always - glass is the surface under a value, never the value.
///
/// Compose these through GlassSurface. A widget that builds its own
/// BackdropFilter is the bug this class exists to prevent.
class BpGlass {
  BpGlass._();

  /// The fill every glass surface is built from, at its step's alpha.
  /// A function, not five constants: a theme change moves all of it.
  static Color tint(double alpha) =>
      const Color.fromARGB(255, 30, 38, 34).withValues(alpha: alpha);

  /// The 1px border on neutral glass.
  static Color hairline([double alpha = 0.12]) =>
      const Color.fromARGB(255, 220, 227, 220).withValues(alpha: alpha);

  /// The light catching the top edge of the pane.
  static Color highlight([double alpha = 0.08]) =>
      const Color.fromARGB(255, 220, 227, 220).withValues(alpha: alpha);

  static const double saturate = 150;
}

/// The five depths, shallowest first. A surface over CONTENT is denser
/// than one over the GROUND - that is what these are, not five greys.
/// Do not go below a step's alpha.
enum GlassDepth {
  /// sits over the ground: web side columns, scrollback, the photo-fit invitation
  panel(alpha: 0.35, blur: 18, radius: BpRadius.card),
  /// recessed in a panel: field wells, segmented controls, rail items
  well(alpha: 0.36, blur: 14, radius: BpRadius.control),
  /// library cards, plan cards, notes, the credits panel, the avatar
  card(alpha: 0.44, blur: 16, radius: BpRadius.card),
  /// over the viewport: the composer, viewport pills, browser chrome
  pill(alpha: 0.48, blur: 18, radius: BpRadius.control),
  /// over everything: the bottom sheet, the device bezel, the tab bar, the web status line
  float(alpha: 0.56, blur: 24, radius: BpRadius.float);

  const GlassDepth({
    required this.alpha,
    required this.blur,
    required this.radius,
  });

  final double alpha;
  final double blur;
  final double radius;
}

/// Tinted glass: same blur, keeps its hue, and the border takes the tint
/// rather than the neutral hairline - which is why the two alphas differ.
enum GlassTint {
  /// the clearance callout, the active plan card
  warn(color: Color(0xFFFFB000), alpha: 0.1, borderAlpha: 0.65),
  /// the pipeline banner, anything about a reference body
  ref(color: Color(0xFF35C6E8), alpha: 0.1, borderAlpha: 0.45),
  /// a pill or segment in its selected state
  active(color: Color(0xFFFFB000), alpha: 0.18, borderAlpha: 0.7);

  const GlassTint({
    required this.color,
    required this.alpha,
    required this.borderAlpha,
  });

  final Color color;
  final double alpha;
  final double borderAlpha;

  Color get fill => color.withValues(alpha: alpha);
  Color get border => color.withValues(alpha: borderAlpha);
}

/// Ambient light BEHIND the glass. Not decoration: a blur with nothing
/// to pick up renders as flat grey, and every panel becomes one slab.
class BpAmbient {
  BpAmbient._();

  static const Color wash0 = Color(0xFFFFB000);
  static const double wash0Alpha = 0.2;
  /// Fractional centre of the wash, as (x, y) of the box.
  static const Alignment wash0At = Alignment(0.56, -0.92);
  /// The wash's extent as a fraction of the box, width
  /// then height - CSS's two radial-gradient
  /// percentages, which is an ellipse and not a circle.
  static const Size wash0Size = Size(1.2, 0.6);
  /// Where the wash has fallen to nothing.
  static const double wash0Stop = 0.62;

  static const Color wash1 = Color(0xFF35C6E8);
  static const double wash1Alpha = 0.16;
  /// Fractional centre of the wash, as (x, y) of the box.
  static const Alignment wash1At = Alignment(-0.8, 0.92);
  /// The wash's extent as a fraction of the box, width
  /// then height - CSS's two radial-gradient
  /// percentages, which is an ellipse and not a circle.
  static const Size wash1Size = Size(0.9, 0.44);
  /// Where the wash has fallen to nothing.
  static const double wash1Stop = 0.66;

  static const Color wash2 = Color(0xFFFFB000);
  static const double wash2Alpha = 0.07;
  /// Fractional centre of the wash, as (x, y) of the box.
  static const Alignment wash2At = Alignment(-0.76, -0.08);
  /// The wash's extent as a fraction of the box, width
  /// then height - CSS's two radial-gradient
  /// percentages, which is an ellipse and not a circle.
  static const Size wash2Size = Size(0.8, 0.4);
  /// Where the wash has fallen to nothing.
  static const double wash2Stop = 0.7;

}

/// Constants the brief pins, so neither client invents one.
class BpMetric {
  BpMetric._();

  static const double tap = 44;
  static const double minWidth = 380;
}
